---
- name: Change user shell to Zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes

- name: Install Zsh configuration
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    force: yes

- name: Install Powerlevel10k configuration
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "{{ ansible_env.HOME}}/.p10k.zsh"
    force: yes

- name: Install distrobution level zsh configurations
  include_tasks: "{{ item }}"
  with_first_found:
    - "configure_{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
