---
- name: Install Zsh and dependancies (Ubuntu 22.04)
  ansible.builtin.apt:
    pkg:
      - curl
      - git
      - zsh
  become: yes

- name: Install Oh My Zsh (Ubuntu 22.04)
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Install Powerlevel10k Zsh theme (Ubuntu 22.04)
  ansible.builtin.shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom}/themes/powerlevel10k"
