---
- name: Install Zsh and Oh My Zsh (ArchLinux rolling)
  pacman:
    name:
      - zsh
      - oh-my-zsh-git
  become: yes

- name: Install Powerlevel10k Zsh theme (ArchLinux rolling)
  command: yay -S --noconfirm zsh-theme-powerlevel10k-git
