---
- name: Install Zsh and Oh My Zsh
  pacman:
    name:
      - zsh
      - oh-my-zsh-git
  become: yes

- name: Install Powerlevel10k Zsh theme
  command: yay -S --noconfirm zsh-theme-powerlevel10k-git
