---
- name: Install Zsh and dependancies (MacOSX 12.3.1)
  community.general.homebrew:
    name:
      - zsh
      - curl
      - git
    state: present

- name: Install Oh My Zsh (MacOSX 12.3.1)
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install Powerlevel10k Zsh theme (MacOSX 12.3.1)
  ansible.builtin.shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
